congreso/config/routes.rb
Congreso::Application.routes.draw do

  resources :votes

  resources :bills

  namespace :admin do
    resources :chambers
    resources :parties
    resources :people do
      get 'update_data', :on => :collection
    end
    resources :sessions do
      resources :text_bookmarks do
        get 'rebuild', :on => :collection
        get 'retag', :on => :collection
        get 'up'
        get 'down'
        get 'transcript'      
        get 'merge_up'
      end
      resources :bookmarks do
        get 'match', :on => :collection
        get 'toggle_matchtyp'
      end   
    end    
    resources :you_tube_videos    
    resources :provinces do
      get 'merge', :on => :collection
    end
  end

  resources :people, :path => 'legisladores' do
    get 'card'
  end

  root :to => 'chambers#index'

  match '~:id' => 'people#show', :as => :person
  match '~:id/card' => 'people#card', :as => :person_card
  match ':id' => 'chambers#show', :as => :chamber
  match ':chamber_name/:period/:meeting' => 'sessions#show', :as => :session
  match ':chamber_name/:period/:meeting/tbk/:text_bookmark_id' => 'text_bookmarks#transcript', :as => :session_text_bookmark_transcript

end

congreso/app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :username, :facebook, :firstname, :lastname, :photo_medium, :photo_small, :twitter, :website, :wikipedia
  attr_accessible :num_speeches

  belongs_to :province
  belongs_to :party
  belongs_to :chamber
  has_many :text_bookmarks

  def fullname
  	"#{lastname}, #{firstname}"
  end

  def to_param
    username || "#{lastname.downcase}_#{firstname.downcase}"
  end

  def to_s
  	fullname
  end

  def match(name)
    lastname == name
  end

  def self.find_by_short_name(short_name)
  	if not short_name.include?('(')
	  	Person.find_by_lastname(short_name.strip.titleize)
	  else
	  	lastname,p = short_name.split('(')
	  	initials = p.scan(/(.)\./).collect {|x| x[0]} 
	  	candidates = Person.find_all_by_lastname(lastname.strip.titleize)
	  	candidates.find do |cand|
	  		ini = cand.firstname.split().collect { |x| x[0]}
	  		if ini == initials
	  			return cand
	  		end
	  	end
	  	puts "Not found: '#{short_name}'"
	  end

  end
end

congreso/app/controllers/admin/people_controller.rb
class Admin::PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    if params[:chamber]
      @chamber = Chamber.find(params[:chamber])
      @people = @people.select {|p| p.chamber == @chamber} if @chamber
    end

    if params[:province]
      @province = Province.find(params[:province])
      @people = @people.select {|p| p.province == @province} if @province
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = get_person(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/card
  def card
    @person = get_person(params[:id])
    respond_to do |format|
      format.html {render :layout => false}
    end
  end

  def update_data
    update_num_speeches
    respond_to do |format|
      format.html { redirect_to admin_people_path, notice: 'Num of speeches updated.' }
    end
  end    

private

  def update_num_speeches
    Person.all.each do |p|
      p.num_speeches = p.text_bookmarks.select {|tb| tb.bookmark && tb.bookmark.matchtyp == 'manual' }.count
      p.save!
    end
  end

  def get_person(id)
    p = params[:id].split('_')

    people = Person.find_all_by_username(p[0])
    people = Person.find_all_by_lastname(p[0].titleize) if people.empty?
    people = Person.find_all(params[:id]) if people.empty?

    if people.length == 1
      people[0]
    elsif p.length < 2
        nil
    else
      people.select{|person| person.firstname.downcase.start_with?(p[1])}[0]
    end
  end      


end

congreso/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    if params[:chamber]
      @chamber = Chamber.find(params[:chamber])
      @people = @people.select {|p| p.chamber == @chamber} if @chamber
    end

    if params[:province]
      @province = Province.find(params[:province])
      @people = @people.select {|p| p.province == @province} if @province
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = get_person(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/card
  def card
    @person = get_person(params[:id])
    respond_to do |format|
      format.html {render :layout => false}
    end
  end

private

  def get_person(id)
    p = params[:id].split('_')

    people = Person.find_all_by_username(p[0])
    people = Person.find_all_by_lastname(p[0].titleize) if people.empty?
    people = Person.find_all(params[:id]) if people.empty?

    if people.length == 1
      people[0]
    elsif p.length < 2
        nil
    else
      people.select{|person| person.firstname.downcase.start_with?(p[1])}[0]
    end
  end      


end

congreso/app/helpers/people_helper.rb
module PeopleHelper
end

congreso/app/views/people/_card.html.erb
<div class="well well-round">
<%= link_to person_path(person) do %>
	<div class="alert alert-success">
		<small><%= person.party.acronym||"<br/>".html_safe %></small>
	</div>


<div>
  <center>
	  <span>
      <%= image_tag person.photo_medium %>
    </span>
    <h5>
      <%= "#{person.lastname.truncate(13)}" %>
    </h5>
    <div>
      <% n = person.num_speeches %>
      <% if n == 0 %>
        <span class="badge">
          sin discursos
        </span>
      <% else %>
        <span class="badge badge-success">
          <%= n %>
        </span>
      <% end %>
    </div>
  </center>

</div>

<% end %>
</div>

congreso/app/views/people/card.html.erb
<div class="well well-round">
<% if @person.party.website %>	
	<%= link_to @person.party.website do %>
		<div class="alert alert-success">
			<%= @person.party.name %>
		</div>
	<% end %>
<% else %>
	<div class="alert alert-success">
		<%= @person.party.name %>
	</div>
<% end %>


<div>
	<span>
	<%= image_tag @person.photo_medium %>
</span>
<h5><%= "#{@person.firstname} #{@person.lastname}" %></h5>
<div>
<%= image_tag "http://cdn1.iconfinder.com/data/icons/yooicons_set01_socialbookmarks/512/social_twitter_box_blue.png", :width => 25 %>
<%= image_tag "http://cdn.androidpolice.com/wp-content/uploads/2013/04/nexusae0_facebook1.png", :width => 25 %>
<%= image_tag "http://www.itsecurityzone.com/wp-content/uploads/2012/05/Email-icon-square.png", :width => 35 %>
</div>

</div>

congreso/app/views/people/index.html.erb
<% content_for :nav do -%>
  <li class="active">
    <%= link_to "legisladores", people_path %>
  </li>
<% end %>

<h3>Legisladores</h3>
<div class="span3 well">
  <ul class="nav nav-list">  
    <li class="<%= (@chamber.nil? && @province.nil?)? 'active' : ''%>"><a href="#">Todos</a></li>   
    <li class="nav-header">
      Por cámara
      <% Chamber.all.each do |chamber| %>
        <% if @chamber == chamber %>
          <li class="active">
            <%= link_to chamber.name, people_path(:province => @province, :chamber => nil) %>
          </li>
        <% else %>
          <% if chamber.disabled %>
            <li><%= chamber.name %></li>
          <% else %>
            <li>
              <%= link_to chamber.name, people_path(:province => @province, :chamber => chamber) %>
            </li>
          <% end %>
        <% end %>        
      <% end %>
    </li>
    <li class="nav-header">
      Por provincia
    </li>
      <% Province.all.each do |prov| %>
        <% if @province == prov %>
          <li class="active">
            <%= link_to prov.name, people_path(:province => nil, :chamber => @chamber) %>
          </li>
        <% else %>
          <li>
            <%= link_to prov.name, people_path(:province => prov, :chamber => @chamber) %>
          </li>
        <% end %>        
      <% end %>
  </ul>
</div>

<div class="span7 well" style="height: 795px; overflow-y:scroll">
  <ul class="thumbnails">
    <% @people.each do |person| %>
      <li class="span2">
          <%= render 'card', :person => person %>
      </li>
    <% end %>
  </ul>
</div>

congreso/app/views/people/show.html.erb
<% content_for :head do -%>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js" %>
<% end %>

<% content_for :nav do -%>
  <li>
    <%= link_to "legisladores", people_path %>
  </li>
  <li class="active">
    <%= link_to(@person) %>
  </li>
<% end %>


<div class="well well-round">
  <% if @person.party.website %>  
    <%= link_to @person.party.website do %>
      <div class="alert alert-success">
        <%= @person.party.name %>
      </div>
    <% end %>
  <% else %>
    <div class="alert alert-success">
      <%= @person.party.name %>
    </div>
  <% end %>
  <div>
    <span>
      <%= image_tag @person.photo_medium %>
    </span>
    <h5><%= "#{@person.firstname} #{@person.lastname}" %></h5>
    <div>
      <%= image_tag "http://cdn1.iconfinder.com/data/icons/yooicons_set01_socialbookmarks/512/social_twitter_box_blue.png", :width => 25 %>
      <%= image_tag "http://cdn.androidpolice.com/wp-content/uploads/2013/04/nexusae0_facebook1.png", :width => 25 %>
      <%= image_tag "http://www.itsecurityzone.com/wp-content/uploads/2012/05/Email-icon-square.png", :width => 35 %>
    </div>
  </div>
</div>

<script>
  var playlist = [];
</script>

<div class="row">
  <div class="span4">
    <div id="vid">
    </div>
  </div>
  <div class="offset4 span4">
    <ul class="nav" style="height: 480px; overflow-y:scroll">
      <% videos = [] %>
      <% @person.text_bookmarks.each do |tbk| %>            
        <% if tbk.session and tbk.bookmark and tbk.bookmark.matchtyp == 'manual' %>
          <% if !videos.include?(tbk.session.video_url) %>
            <li><span class="label label-important"><%= tbk.session.date.strftime('%d/%m/%Y') %></span></li>
            <% videos << tbk.session.video_url %>
          <% end %>
          <li id="<%= tbk.bookmark.pos %>">

            <a class="thumbnail" style="text-decoration:none" href="javascript:seek(<%= tbk.bookmark.pos %>,'<%= session_text_bookmark_transcript_path(tbk.session.chamber.name,tbk.session.period,tbk.session.meeting,tbk) %>',<%= videos.length-1 %>)">
              <table>
                <tr>
                  <td rowspan='2'>
                    <img src="<%= @person.photo_small %>" class="img-polaroid"/>
                  </td>
                  <td>
                    <b><%= tbk.section %></b>
                  </td>
                </tr>                      
              </table>
            </a> 
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div id="info" style="display:none">
  <div class="span11 well">
    <p id="text"></p>
    <button class="btn" disabled>Descargar video</button>
    <button class="btn" disabled>Descargar .doc</button>
    <button class="btn" disabled><%= image_tag "http://www.ecreativeim.com/blog/wp-content/uploads/2011/05/facebook-like-icon.png", :width => 25 %></button>
  </div>
</div>


<script src="http://www.hcdn.gov.ar/system/modules/ar.gov.hcdn/resources/jwplayer-premium/jwplayer.js"></script>
<script> jwplayer.key="f449YUYx6rSnWyS5eFa0f8/2NI60KlVjkkGFjKZ6154="</script>

<script>

  var playlist = [
    <%= videos.collect {|v| "{file: '#{v}'}" }.join(',').html_safe %>
  ];

  jwplayer('vid').setup({
      playlist:  playlist,
      width: '600',
      height: '480'
  });

  var seek_to = null;
  jwplayer('vid').onPlay(function() {
    if(seek_to != null) {
      jwplayer('vid').seek(seek_to);
      seek_to = null;
    }
  });

  var curr_video_index = null;
  function seek(pos,transcript_url,video_index) {
    var player = jwplayer('vid');
    if(curr_video_index != video_index) {
      seek_to = pos;
      player.playlistItem(video_index);
    } else {
      player.seek(pos);
    }
    $("#info").show();
    $.get(transcript_url, function(resp) {
      $("#text").html(resp);
    });
  }
</script>