congreso/config/routes.rb
Congreso::Application.routes.draw do

  resources :votes

  resources :bills

  namespace :admin do
    resources :chambers
    resources :parties
    resources :people do
      get 'update_data', :on => :collection
    end
    resources :sessions do
      resources :text_bookmarks do
        get 'rebuild', :on => :collection
        get 'retag', :on => :collection
        get 'up'
        get 'down'
        get 'transcript'      
        get 'merge_up'
      end
      resources :bookmarks do
        get 'match', :on => :collection
        get 'toggle_matchtyp'
      end   
    end    
    resources :you_tube_videos    
    resources :provinces do
      get 'merge', :on => :collection
    end
  end

  resources :people, :path => 'legisladores' do
    get 'card'
  end

  root :to => 'chambers#index'

  match '~:id' => 'people#show', :as => :person
  match '~:id/card' => 'people#card', :as => :person_card
  match ':id' => 'chambers#show', :as => :chamber
  match ':chamber_name/:period/:meeting' => 'sessions#show', :as => :session
  match ':chamber_name/:period/:meeting/tbk/:text_bookmark_id' => 'text_bookmarks#transcript', :as => :session_text_bookmark_transcript

end

congreso/app/models/party.rb
class Party < ActiveRecord::Base
  attr_accessible :facebook, :name, :photo_medium, :photo_small, :twitter, :website, :wikipedia, :acronym
  has_many :people


  def to_s
  	name
  end
end

congreso/app/controllers/admin/parties_controller.rb
class PartiesController < ApplicationController
  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all.sort_by { |p| p.name.downcase }
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parties }
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @party = Party.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new
    @party = Party.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find(params[:id])
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(params[:party])

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    @party = Party.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end
end

congreso/app/helpers/parties_helper.rb
module PartiesHelper
end

congreso/app/views/admin/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>  
  <div class="field">
    <%= f.label :acronym %><br />
    <%= f.text_field :acronym %>
  </div>
  <div class="field">
    <%= f.label :photo_small %><br />
    <%= f.text_field :photo_small %>
  </div>
  <div class="field">
    <%= f.label :photo_medium %><br />
    <%= f.text_field :photo_medium %>
  </div>
  <div class="field">
    <%= f.label :wikipedia %><br />
    <%= f.text_field :wikipedia %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

congreso/app/views/admin/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

congreso/app/views/admin/parties/index.html.erb
<h1>Parties</h1>

<table>
  <tr>
    <th>Photo</th>
    <th>Name</th>
    <th>Acronym</th>
    <th>People</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parties.each do |party| %>
  <tr>
    <td>
        <% if party.photo_medium %>
        <%= image_tag party.photo_medium, :width => 30, :height => 30 %>
        <% else %>
        &nbsp;
        <% end %>
    </td>
    <td><%= party.name %></td>
    <td><%= party.acronym %></td>
    <td><%= party.people.length %></td>
    <td><%= party.website %></td>
    <td><%= link_to 'Show', party %></td>
    <td><%= link_to 'Edit', edit_party_path(party) %></td>
    <td><%= link_to 'Destroy', party, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Party', new_party_path %>

congreso/app/views/admin/parties/new.html.erb
<h1>New party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

congreso/app/views/admin/parties/show.html.erb
<p>
  <b>Name:</b>
  <%= @party.name %>
</p>

<p>
  <b>Photo small:</b>
  <%= @party.photo_small %>
</p>

<p>
  <b>Photo medium:</b>
  <%= @party.photo_medium %>
</p>

<p>
  <b>Wikipedia:</b>
  <%= @party.wikipedia %>
</p>

<p>
  <b>Facebook:</b>
  <%= @party.facebook %>
</p>

<p>
  <b>Twitter:</b>
  <%= @party.twitter %>
</p>

<p>
  <b>Website:</b>
  <%= @party.website %>
</p>


<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>