congreso/config/routes.rb
Congreso::Application.routes.draw do

  resources :votes

  resources :bills

  namespace :admin do
    resources :chambers
    resources :parties
    resources :people do
      get 'update_data', :on => :collection
    end
    resources :sessions do
      resources :text_bookmarks do
        get 'rebuild', :on => :collection
        get 'retag', :on => :collection
        get 'up'
        get 'down'
        get 'transcript'      
        get 'merge_up'
      end
      resources :bookmarks do
        get 'match', :on => :collection
        get 'toggle_matchtyp'
      end   
    end    
    resources :you_tube_videos    
    resources :provinces do
      get 'merge', :on => :collection
    end
  end

  resources :people, :path => 'legisladores' do
    get 'card'
  end

  root :to => 'chambers#index'

  match '~:id' => 'people#show', :as => :person
  match '~:id/card' => 'people#card', :as => :person_card
  match ':id' => 'chambers#show', :as => :chamber
  match ':chamber_name/:period/:meeting' => 'sessions#show', :as => :session
  match ':chamber_name/:period/:meeting/tbk/:text_bookmark_id' => 'text_bookmarks#transcript', :as => :session_text_bookmark_transcript

end

congreso/app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  attr_accessible :typ, :pos, :length, :textpos, :textlength, :title, :score, :matchtyp
  belongs_to :text_bookmark
  belongs_to :session
end

congreso/app/controllers/admin/bookmarks_controller.rb
# encoding: UTF-8
class Admin::BookmarksController < ApplicationController
  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @session = Session.find(params[:session_id])
    @bookmarks = @session.bookmarks
    @text_bookmarks = @session.text_bookmarks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end

  def match
    @session = Session.find(params[:session_id])
    @session.match_bookmarks
    respond_to do |format|
      format.html { redirect_to session_bookmarks_path(@session), notice: 'Bookmarks were successfully matched.' }    
      format.json { render json: @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.json
  def new
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def toggle_matchtyp
    @bookmark = Bookmark.find(params[:bookmark_id])
    if @bookmark.matchtyp == 'manual'
      @bookmark.matchtyp = 'auto'
    else
      @bookmark.matchtyp = 'manual'
    end
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.text { render text: @bookmark.matchtyp }
        format.json { render json: @bookmark, status: :updated, location: session_bookmark_path(@bookmark.session,@bookmark) }
      else
        format.html { render action: "edit" }
        format.text { render text: "???" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end    


  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(params[:bookmark])

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render json: @bookmark, status: :created, location: @bookmark }
      else
        format.html { render action: "new" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.json
  def update
    @bookmark = Bookmark.find(params[:id])
    respond_to do |format|      
      @bookmark.text_bookmark = TextBookmark.find(params[:bookmark][:text_bookmark_id])
      if @bookmark.update_attributes(params[:bookmark].except(:text_bookmark_id))
        format.html { redirect_to session_bookmark_path(@bookmark.session,@bookmark), notice: 'Bookmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :no_content }
    end
  end
end

congreso/app/controllers/bookmarks_controller.rb
# encoding: UTF-8
class BookmarksController < ApplicationController
  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @session = Session.find(params[:session_id])
    @bookmarks = @session.bookmarks
    @text_bookmarks = @session.text_bookmarks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end

  def match
    @session = Session.find(params[:session_id])
    @session.match_bookmarks
    respond_to do |format|
      format.html { redirect_to session_bookmarks_path(@session), notice: 'Bookmarks were successfully matched.' }    
      format.json { render json: @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.json
  def new
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def toggle_matchtyp
    @bookmark = Bookmark.find(params[:bookmark_id])
    if @bookmark.matchtyp == 'manual'
      @bookmark.matchtyp = 'auto'
    else
      @bookmark.matchtyp = 'manual'
    end
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.text { render text: @bookmark.matchtyp }
        format.json { render json: @bookmark, status: :updated, location: session_bookmark_path(@bookmark.session,@bookmark) }
      else
        format.html { render action: "edit" }
        format.text { render text: "???" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end    


  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(params[:bookmark])

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render json: @bookmark, status: :created, location: @bookmark }
      else
        format.html { render action: "new" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.json
  def update
    @bookmark = Bookmark.find(params[:id])
    respond_to do |format|      
      @bookmark.text_bookmark = TextBookmark.find(params[:bookmark][:text_bookmark_id])
      if @bookmark.update_attributes(params[:bookmark].except(:text_bookmark_id))
        format.html { redirect_to session_bookmark_path(@bookmark.session,@bookmark), notice: 'Bookmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :no_content }
    end
  end
end

congreso/app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

congreso/app/views/admin/bookmarks/_form.html.erb
<%= form_for([@bookmark.session,@bookmark]) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matchtyp %><br />
    <%= f.select(:matchtyp, [['',nil],['manual','manual'],['auto','auto']]) %>
  </div>
  <div class="field">
    <%= f.label :pos %><br />
    <%= f.number_field :pos %>
  </div>
  <div class="field">
    <%= f.label :text_bookmark_id %><br />
    <%= f.select(:text_bookmark_id, @bookmark.session.text_bookmarks.all.select {|tbk| !tbk.person.nil?}.collect { |tbk| [tbk.person,tbk.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

congreso/app/views/admin/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', session_bookmark_path(@bookmark.session,@bookmark) %> |
<%= link_to 'Back', :back %>

congreso/app/views/admin/bookmarks/index.html.erb
<% content_for :head do -%>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js" %>
  <style>
    .manual {
      color: green;
      font-weight: bold;
    }
    .pos_selected {
      background-color: pink;
    }
  </style>
<% end %>

<h1>Listing bookmarks</h1>

<div class="row">
<div class="span4" style="height: 480px; overflow-y:scroll">
<table>
  <tr>
    <th>Pos</th>
    <th>Transcript person</th>
    <th></th>
    <th></th>
  </tr>

<% @bookmarks.each do |bookmark| %>
  <tr id='<%= "bookmark_#{bookmark.id}" %>'>
    <td class='pos'>
      <%= link_to bookmark.pos, "javascript:seek(#{bookmark.id},#{bookmark.pos},'#{(bookmark.text_bookmark)? admin_session_text_bookmark_transcript_path(@session,bookmark.text_bookmark) : nil}')" %>
    </td>    
    <td class='speaker'>
        <%= link_to("javascript:toggle(#{bookmark.id},'#{admin_session_bookmark_toggle_matchtyp_path(bookmark.session,bookmark, :format => :text)}')", :class => [bookmark.matchtyp,'person']) do %>
            <% if bookmark.text_bookmark and bookmark.text_bookmark.person %>
              <%= bookmark.text_bookmark.person %>
            <% else %>
              &nbsp;              
            <% end %>
        <% end %>
        <span class="arrows">        
          <% if bookmark.text_bookmark and bookmark.text_bookmark.person %>
              <%= link_to("javascript:moveSpeaker('#{admin_session_text_bookmark_up_path(bookmark.session,bookmark.text_bookmark, :format => :json)}')") do %>
                <i class="icon-arrow-up"></i>
              <% end %>
              <%= link_to("javascript:moveSpeaker('#{admin_session_text_bookmark_down_path(bookmark.session,bookmark.text_bookmark, :format => :json)}')") do %>
                <i class="icon-arrow-down"></i>
              <% end %>
          <% end %>
        </span>
    </td>
    <td><%= link_to 'Edit', edit_admin_session_bookmark_path(@session,bookmark) %></td>
  </tr>
<% end %>
</table>
</div>

<div class="span4">
  <div id="vid"></div>
  <button class="btn" onclick="manualseek(-10)">&lt;&lt;</button>
  <button class="btn" onclick="manualseek(10)">&gt;&gt;</button>

</div>  

</div>

<div class="row">
  <div class="span6">
    <div id="text"></div>
</div>

<% if @session.video_url and not @session.video_url.empty? %>

  <script src="http://www.hcdn.gov.ar/system/modules/ar.gov.hcdn/resources/jwplayer-premium/jwplayer.js"></script>
  <script> jwplayer.key="f449YUYx6rSnWyS5eFa0f8/2NI60KlVjkkGFjKZ6154="</script>

  <script>

    jwplayer('vid').setup({
        file: '<%= @session.video_url %>',
        width: '600',
        height: '480'
    });


    function moveSpeaker(url) {
      $.getJSON(url, function(resp) {
        var html = $("#bookmark_"+resp.prev_bookmark+" .speaker a").html();
        $("#bookmark_"+resp.prev_bookmark+" .speaker a.person").html("");
        $("#bookmark_"+resp.current_bookmark+" .speaker a.person").html(html);

        var html = $("#bookmark_"+resp.prev_bookmark+" .speaker .arrows").html();
        $("#bookmark_"+resp.prev_bookmark+" .speaker .arrows").html("");
        $("#bookmark_"+resp.current_bookmark+" .speaker .arrows").html(html);      
      });
    }


    var previd = null;
    function seek(id,pos,transcript_url) {
      if(previd != null) {
        $("#bookmark_"+previd+" .pos a").removeClass("pos_selected");
      }
      $("#bookmark_"+id+" .pos a").addClass("pos_selected");
      previd = id;
      jwplayer('vid').seek(pos);
      if(transcript_url != "") {
        $.get(transcript_url, function(resp) {
          $("#text").html(resp);
        });
      }
    }

    function manualseek(ofs) {
      jwplayer('vid').seek(jwplayer('vid').getPosition() + ofs);
    }

  </script>

<% else %>

  <script>
    var vids = [
      <%= @session.you_tube_videos.collect {|video| "'#{video.video_id}'"}.join(',').html_safe %>
    ];

    var lengths = [
      <%= @session.you_tube_videos.collect {|video| video.length}.join(',') %>
    ];

    var params = { allowScriptAccess: "always" };
    var atts = { id: "vid" };
    
    swfobject.embedSWF("http://www.youtube.com/v/" + vids[0] + "?enablejsapi=1&playerapiid=ytplayer&version=3",
                       "vid", "640", "480", "8", null, null, params, atts);

    var ytplayer;
    function onYouTubePlayerReady(playerId) {
      ytplayer = document.getElementById("vid");
    }

    var previd = null;
    var prevvid = vids[0];
    var currpos = null;
    function seek(id,pos,transcript_url) {
      currpos = pos;
      for(i=0; i<vids.length; i++) {
        if(pos - lengths[i] < 0) {
          break;
        }
        pos -= lengths[i];
      }
      if(prevvid != vids[i]) {
        ytplayer.loadVideoById(vids[i]);
        prevvid = vids[i];
      }
      ytplayer.seekTo(pos);

      if(previd != null) {
        $("#bookmark_"+previd+" .pos a").removeClass("pos_selected");
      }
      $("#bookmark_"+id+" .pos a").addClass("pos_selected");
      previd = id;
      //jwplayer('vid').seek(pos);
      if(transcript_url != "") {
        $.get(transcript_url, function(resp) {
          $("#text").html(resp);
        });
      }
    }

    function manualseek(ofs) {
      ytplayer.seekTo(currpos+ofs);
      currpos += ofs;
    }

  </script>

<% end %>

<script>
    function toggle(id, url) {
      $.get(url, function(resp) {
        var e = $("#bookmark_"+id+" .speaker a.person");
        e.removeClass("manual");
        e.removeClass("auto");
        e.addClass(resp);
      });
    }

</script>

congreso/app/views/admin/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

congreso/app/views/admin/bookmarks/show.html.erb
<p>
  <b>Type:</b>
  <%= @bookmark.type %>
</p>

<p>
  <b>Pos:</b>
  <%= @bookmark.pos %>
</p>

<p>
  <b>Session:</b>
  <%= @bookmark.session_id %>
</p>

<p>
  <b>Text Bookmark:</b>
  <%= @bookmark.text_bookmark.person if @bookmark.text_bookmark %>
</p>

<p>
  <b>Person:</b>
  <%= @bookmark.person_id %>
</p>

<p>
  <b>Title:</b>
  <%= @bookmark.title %>
</p>

<%= link_to 'Edit', edit_session_bookmark_path(@bookmark.session,@bookmark) %> |
<%= link_to 'Back', :back %>